# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30e0c7cee85746001ff1fe1fe18f0c550679a947fa6c069ac3ed5a709eabba9cf59de68e0fa850d41a261c4261d38d831fd4d7e328a7395e20bb52a42e9c952d

test:
  secret_key_base: e8d816eab824ba0cb0ab192c9cd4c2bcfea4ce8ec9788df6ce57881705a1e1a7fffd70c443f610875a99f41b174b04d3e4c55e6d251a673034b086e670204eaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
